kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: expressapp1
spec:
  replicas:
  template:
    metadata:
      name: expressapp1
      labels:
        app: expressapp1
        role: expressapp1
        env: production
    spec:
      containers:
      - name: expressapp1
        image: shahzeb799/expressapp1:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - name: expressapp1
          containerPort: 3000
