kind: Service
apiVersion: v1
metadata:
  name: expressapp1
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
  loadBalancerIP: 35.196.246.45
  selector:
    app: expressapp1
    role: expressapp1
status:
  loadBalancer:
    ingress:
    - ip: 35.196.246.45